### PR TITLE
Python Language Bindings

### PR DESCRIPTION
**Pull request by YasogaN**
Hi,

I have added python language bindings for the program (i haven't tested it thoroughly just the start command)
I just wanted to make sure if you have any issues with the project structure. (i had to put everything in `/src/` because it wouldn't work otherwise)

I am a beginner to C so if u have any advice for me to retain the original project structure, I would be happy to listen. Also if u have a specific project structure in mind, please let me know

PS: I've been trying to do this since the day u released the library and i was finally able to.

### CODE REVIEW

**Comment by keifufu** [comment]
Hey, I will look into this tomorrow or the following days, thanks for the contribution!

I just want to ask if you ran into any trouble with the library itself? Especially the desktop player support since I have barely tested it on Windows.

This is also quite impressive given your experience!! Congrats!

Regarding structure and such I will give feedback once I properly looked into it ^^

**Comment by keifufu** [comment]
A few things to note
- This should build a Python package installable via pip
- Needs to work on both windows and linux
- I could not find any build instructions for this (the generated .py file should be .gitignore'd and generated as a build step)
- Usage examples would also be nice
- moving the python bindings out of src/ and into /bindings/python or whatever is probably also no issue

In case you haven't been using it, the library is built using the `Makefile`. You can also use it on Windows with GnuWin32. It basically just executes a bunch of commands in a row so this is where I would put any build steps needed for the python bindings.

I'll try and get this to work for myself on Linux and then see where I can help with the points above ^^

**Comment by YasogaN** [comment]
> I just want to ask if you ran into any trouble with the library itself? Especially the desktop player support since I have barely tested it on Windows.

I did run into a bit of trouble with `dp_windows.cpp` because the original library was using `utc_clock` instead of `system_clock` and that gave me ton of build errors so I made the necessary changes (https://github.com/keifufu/WebNowPlaying-Library/pull/1/commits/a4fbadae31251bd669e42a53d935e59b633bd5af)

And the other issue I ran into while building the `.pyd` package was that `dp_windows.cpp` and `dp_linux.c` conflicts with each other because they both define the same functions. So for the moment, I am not including `dp_linux.c` in the `.pyd`. However if this breaks functionality during further testing, I will find a solution for it.

**Comment by keifufu** [comment]
Are you able to get it to build with the files in /bindings/python?

setuptools doesn't seem too happy with files in parent directories, so I'd just work around it like this:

```sh
cp -R ../../src src
cp wnp.i src/wnp.i
swig -python -outdir . -o src/wnp_wrap.c src/wnp.i
python3 setup.py build
rm -rf src
```

**Comment by YasogaN** [comment]
> Are you able to get it to build with the files in /bindings/python?

Yeah, I was able to get it to work on windows. I am currently making the `__init__.py` for the module

**Comment by keifufu** [comment]
Have you tried using ctypes.CDLL btw? instead of swig

**Comment by YasogaN** [comment]
> Have you tried using ctypes.CDLL btw? instead of swig

No, Swig was my first option because it was easier to deal with.

**Comment by keifufu** [comment]
Compiling a shared library to be imported by ctypes would be significantly easier for me, I will be experimenting with it.

**Comment by keifufu** [comment]
Update: continue with swig, it handles a lot of annoying parts ^^

**Comment by YasogaN** [comment]
So Current Status:
- [x] builds a wheel package (not tested in linux)
- [x] Fully Tested
- [ ] Examples

so yeah, ill be testing this and ill let you know how it works on windows. Then ill move on to adding the examples.

**Comment by keifufu** [comment]
I'll give you time to work things out on your own. Once you're happy with the work I will commit my changes ^^

**Comment by YasogaN** [comment]
I am getting a circular imports error and I have no idea how to battle that (Help is very much appreciated). Only viable option (as it seems to me) would be to remove the `__init__.py` and rename `wnp_wrapper.py` to `__init__.py` as build step. However it is also important to note that this would break functionality for people moving from PyWNP to this Library. 

How do you want me to proceed?

**Comment by keifufu** [comment]
Keep it similar to the C functions, no need to wrap it in a way that mimics current PyWNP functions.

Wrappers would be good to automatically wnp_lock and wnp_unlock when reading variables though

**Comment by YasogaN** [comment]
> So Current Status:
> 
> - [x]  builds a wheel package (not tested in linux)
> - [x]  Fully Tested
> - [ ]  Examples
> 
> so yeah, ill be testing this and ill let you know how it works on windows. Then ill move on to adding the examples.


Status Upadate:

I tested the `whl` package and it works great now. I also moved all the functions i had (that were to ensure backwards compatibility for PyWNP users) from `__init__.py` to `functions.py` (this removed the circular import issue).

So now developers can use use the `functions` sub module if they are moving from PyWNP (for minimal code changes) or they can use the `wnp_wrapper` sub module. 

So now i will be moving to the next stage of adding examples

**Comment by YasogaN** [comment]
Just in case your wondering what happened to me, basically I'm stuck with callbacks (I got this while i was testing). So the moment i find a fix for that, I'll commit the examples and the necessary changes and request the review. 

Sorry for he late response, I got carried away with some coursework ; - ;

**Comment by YasogaN** [comment]
I can't seem to find a fix for callbacks. Also i found errors spewing out when doing `wnp_get_all_players()`. If you could take a look at it on your free time, I would greatly appreciate it! It's mainly because i dont have much experience in `c` and its basically half alien to me. 

- Issues when doing callbacks:
Events function can be initialized and passed through to the start command but when assigning callbacks to events errors are introduced. 
eg: 
```
events.on_player_added = on_player_added
    ^^^^^^^^^^^^^^^^^^^^^^
TypeError: in method 'wnp_events_on_player_added_set', argument 2 of type 'void (*)(struct wnp_player *)'
```

- Issues with `wnp_get_all_players()`:
Unable to create a object for the argument in the function
```
    players = wnp_wrapper.wnp_player * wnp_wrapper.WNP_MAX_PLAYERS
              ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for *: 'type' and 'int'
```

After thorough testing, These are the only issues which arose. All other functions and commands are fully functional.

**Comment by keifufu** [comment]
The structure of this library has changed a lot recently. Are you still interested in Python bindings?

**Comment by YasogaN** [comment]
Hi, I am a bit tied up on some assignments these days. Due to the structure been changed, I will have to take a look at this again.  So i dont think I will be able to contribute to this anytime soon. 
Sorry for having this up PR up for nearly 10 months.

**Pull request closed without merging**
